#!/bin/bash
cd $(dirname $(readlink -m ${0})) || exit

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && mkdir -p ${2%/*} && ln -sfvT "$1" $2; }


link "$PWD/urxvt-focus-events" ~/.urxvt/ext/focus-events
